const dotenv = require('dotenv');
const path = require('path');

// Load env files from common startup directories so the API works
// whether started from project root or from the `api` folder.
const envCandidates = [
  path.resolve(process.cwd(), '.env'),
  path.resolve(process.cwd(), 'backend.env'),
  path.resolve(__dirname, '../../.env'),
  path.resolve(__dirname, '../../backend.env'),
];

for (const envPath of envCandidates) {
  dotenv.config({ path: envPath });
}

function required(name, fallback) {
  const v = process.env[name] || fallback;
  if (!v) throw new Error(`Variável de ambiente ausente: ${name}`);
  return v;
}

module.exports = {
  BASE_URL: required('SOLARMAN_BASE_URL', 'https://globalapi.solarmanpv.com'),
  APP_ID: required('SOLARMAN_APP_ID'),
  APP_SECRET: required('SOLARMAN_APP_SECRET'),
  ORG_ID: process.env.SOLARMAN_ORG_ID || undefined,
  EMAIL: process.env.SOLARMAN_EMAIL || undefined,
  USERNAME: process.env.SOLARMAN_USERNAME || undefined,
  MOBILE: process.env.SOLARMAN_MOBILE || undefined,
  PASSWORD: required('SOLARMAN_PASSWORD'),
  TOKEN_CACHE_PATH: process.env.SOLARMAN_TOKEN_CACHE || path.join('var', 'token.json'),
  SOLIS_BASE_URL: process.env.SOLIS_BASE_URL || 'https://www.soliscloud.com:13333',
  SOLIS_API_ID: process.env.SOLIS_API_ID || undefined,
  SOLIS_API_SECRET: process.env.SOLIS_API_SECRET || undefined,
  SOLIS_STATION_ID: process.env.SOLIS_STATION_ID || undefined,
  DEYE_BASE_URL: process.env.DEYE_BASE_URL || 'https://us1-developer.deyecloud.com/v1.0',
  DEYE_APP_ID: process.env.DEYE_APP_ID || undefined,
  DEYE_APP_SECRET: process.env.DEYE_APP_SECRET || undefined,
  DEYE_EMAIL: process.env.DEYE_EMAIL || undefined,
  DEYE_USERNAME: process.env.DEYE_USERNAME || undefined,
  DEYE_MOBILE: process.env.DEYE_MOBILE || undefined,
  DEYE_COUNTRY_CODE: process.env.DEYE_COUNTRY_CODE || undefined,
  DEYE_PASSWORD: process.env.DEYE_PASSWORD || undefined,
  DEYE_COMPANY_ID: process.env.DEYE_COMPANY_ID || undefined,
  DEYE_TOKEN_CACHE_PATH: process.env.DEYE_TOKEN_CACHE || path.join('var', 'deye-token.json'),
  AURORA_VISION_BASE_URL: process.env.AURORA_VISION_BASE_URL || 'https://api.auroravision.net/api/rest',
  AURORA_VISION_API_KEY: process.env.AURORA_VISION_API_KEY || undefined,
  AURORA_VISION_USERNAME: process.env.AURORA_VISION_USERNAME || undefined,
  AURORA_VISION_PASSWORD: process.env.AURORA_VISION_PASSWORD || undefined,
  AURORA_VISION_MOCK: String(process.env.AURORA_VISION_MOCK || 'true').toLowerCase() === 'true',
  AURORA_VISION_STATIONS_ENDPOINT: process.env.AURORA_VISION_STATIONS_ENDPOINT || '/sites',
  SOLPLANET_MONITOR_BASE_URL: process.env.SOLPLANET_MONITOR_BASE_URL || 'https://internation-pro-cloud.solplanet.net',
  SOLPLANET_MONITOR_APP_KEY: process.env.SOLPLANET_MONITOR_APP_KEY || undefined,
  SOLPLANET_MONITOR_APP_SECRET: process.env.SOLPLANET_MONITOR_APP_SECRET || undefined,
  SOLPLANET_MONITOR_USERNAME: process.env.SOLPLANET_MONITOR_USERNAME || undefined,
  SOLPLANET_MONITOR_PASSWORD: process.env.SOLPLANET_MONITOR_PASSWORD || undefined,
  SOLPLANET_MONITOR_TOKEN: process.env.SOLPLANET_MONITOR_TOKEN || undefined,
  SOLPLANET_MONITOR_MOCK: String(process.env.SOLPLANET_MONITOR_MOCK || 'true').toLowerCase() === 'true',
  SOLPLANET_MONITOR_LOGIN_ENDPOINT: process.env.SOLPLANET_MONITOR_LOGIN_ENDPOINT || '/api/login',
  SOLPLANET_MONITOR_LOGIN_METHOD: process.env.SOLPLANET_MONITOR_LOGIN_METHOD || 'POST',
  SOLPLANET_MONITOR_LOGIN_BODY_USER_FIELD: process.env.SOLPLANET_MONITOR_LOGIN_BODY_USER_FIELD || 'username',
  SOLPLANET_MONITOR_LOGIN_BODY_PASS_FIELD: process.env.SOLPLANET_MONITOR_LOGIN_BODY_PASS_FIELD || 'password',
  SOLPLANET_MONITOR_TOKEN_FIELD: process.env.SOLPLANET_MONITOR_TOKEN_FIELD || 'token',
  SOLPLANET_MONITOR_TOKEN_HEADER: process.env.SOLPLANET_MONITOR_TOKEN_HEADER || 'Authorization',
  SOLPLANET_MONITOR_TOKEN_PREFIX: process.env.SOLPLANET_MONITOR_TOKEN_PREFIX || 'Bearer ',
  SOLPLANET_MONITOR_STATIONS_ENDPOINT: process.env.SOLPLANET_MONITOR_STATIONS_ENDPOINT || '/monitoring/stations',
  TSUNESS_BASE_URL: process.env.TSUNESS_BASE_URL || 'https://api.tsuness.com',
  TSUNESS_API_KEY: process.env.TSUNESS_API_KEY || undefined,
  TSUNESS_API_SECRET: process.env.TSUNESS_API_SECRET || undefined,
  TSUNESS_USERNAME: process.env.TSUNESS_USERNAME || undefined,
  TSUNESS_PASSWORD: process.env.TSUNESS_PASSWORD || undefined,
  TSUNESS_TOKEN: process.env.TSUNESS_TOKEN || undefined,
  TSUNESS_MOCK: String(process.env.TSUNESS_MOCK || 'true').toLowerCase() === 'true',
  TSUNESS_STATIONS_ENDPOINT: process.env.TSUNESS_STATIONS_ENDPOINT || '/monitoring/stations',
  ISOLARCLOUD_BASE_URL: process.env.ISOLARCLOUD_BASE_URL || 'https://gateway.isolarcloud.com',
  ISOLARCLOUD_APP_KEY: process.env.ISOLARCLOUD_APP_KEY || undefined,
  ISOLARCLOUD_ACCESS_KEY: process.env.ISOLARCLOUD_ACCESS_KEY || undefined,
  ISOLARCLOUD_RSA_PRIVATE_KEY: process.env.ISOLARCLOUD_RSA_PRIVATE_KEY || undefined,
  ISOLARCLOUD_USERNAME: process.env.ISOLARCLOUD_USERNAME || undefined,
  ISOLARCLOUD_PASSWORD: process.env.ISOLARCLOUD_PASSWORD || undefined,
  ISOLARCLOUD_TOKEN: process.env.ISOLARCLOUD_TOKEN || undefined,
  ISOLARCLOUD_MOCK: String(process.env.ISOLARCLOUD_MOCK || 'true').toLowerCase() === 'true',
  ISOLARCLOUD_LOGIN_ENDPOINT: process.env.ISOLARCLOUD_LOGIN_ENDPOINT || '/openapi/login',
  ISOLARCLOUD_LOGIN_METHOD: process.env.ISOLARCLOUD_LOGIN_METHOD || 'POST',
  ISOLARCLOUD_LOGIN_BODY_USER_FIELD: process.env.ISOLARCLOUD_LOGIN_BODY_USER_FIELD || 'userName',
  ISOLARCLOUD_LOGIN_BODY_PASS_FIELD: process.env.ISOLARCLOUD_LOGIN_BODY_PASS_FIELD || 'password',
  ISOLARCLOUD_TOKEN_FIELD: process.env.ISOLARCLOUD_TOKEN_FIELD || 'token',
  ISOLARCLOUD_TOKEN_HEADER: process.env.ISOLARCLOUD_TOKEN_HEADER || 'Authorization',
  ISOLARCLOUD_TOKEN_PREFIX: process.env.ISOLARCLOUD_TOKEN_PREFIX || 'Bearer ',
  ISOLARCLOUD_STATIONS_ENDPOINT: process.env.ISOLARCLOUD_STATIONS_ENDPOINT || '/openapi/powerStation/list',
  ELEKEEPER_BASE_URL: process.env.ELEKEEPER_BASE_URL || 'https://intl-developer.saj-electric.com',
  ELEKEEPER_DEVELOPER_ID: process.env.ELEKEEPER_DEVELOPER_ID || undefined,
  ELEKEEPER_API_KEY: process.env.ELEKEEPER_API_KEY || undefined,
  ELEKEEPER_API_SECRET: process.env.ELEKEEPER_API_SECRET || undefined,
  ELEKEEPER_USERNAME: process.env.ELEKEEPER_USERNAME || undefined,
  ELEKEEPER_PASSWORD: process.env.ELEKEEPER_PASSWORD || undefined,
  ELEKEEPER_TOKEN: process.env.ELEKEEPER_TOKEN || undefined,
  ELEKEEPER_MOCK: String(process.env.ELEKEEPER_MOCK || 'true').toLowerCase() === 'true',
  ELEKEEPER_LOGIN_ENDPOINT: process.env.ELEKEEPER_LOGIN_ENDPOINT || '/openapi/auth/login',
  ELEKEEPER_LOGIN_METHOD: process.env.ELEKEEPER_LOGIN_METHOD || 'POST',
  ELEKEEPER_LOGIN_BODY_USER_FIELD: process.env.ELEKEEPER_LOGIN_BODY_USER_FIELD || 'username',
  ELEKEEPER_LOGIN_BODY_PASS_FIELD: process.env.ELEKEEPER_LOGIN_BODY_PASS_FIELD || 'password',
  ELEKEEPER_TOKEN_FIELD: process.env.ELEKEEPER_TOKEN_FIELD || 'token',
  ELEKEEPER_TOKEN_HEADER: process.env.ELEKEEPER_TOKEN_HEADER || 'Authorization',
  ELEKEEPER_TOKEN_PREFIX: process.env.ELEKEEPER_TOKEN_PREFIX || 'Bearer ',
  ELEKEEPER_STATIONS_ENDPOINT: process.env.ELEKEEPER_STATIONS_ENDPOINT || '/openapi/power/stations',
};
